# Generated by Django 5.1.1 on 2024-11-14 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_contributors_permission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issues',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Low', max_length=50),
        ),
        migrations.AlterField(
            model_name='issues',
            name='status',
            field=models.CharField(choices=[('To-Do', 'To Do'), ('In_progress', 'In Progress'), ('Completed', 'Completed')], default='To-Do', max_length=50),
        ),
        migrations.AlterField(
            model_name='issues',
            name='tag',
            field=models.CharField(choices=[('Bug', 'Bug'), ('Enhancement', 'Enhancement'), ('Task', 'Task')], default='Task', max_length=50),
        ),
    ]
