# Generated by Django 5.1.1 on 2024-11-14 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_issues_assignee_user_alter_issues_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issues',
            old_name='assignee_user',
            new_name='issue_assignee',
        ),
        migrations.RenameField(
            model_name='issues',
            old_name='author',
            new_name='issue_author',
        ),
    ]
